<?php
/**
 * Навигационная цепочка для материала.
 * 
 * Часть макета страницы.
 * 
 * @author Anton Tivonenko <anton.tivonenko@gmail.com>
 * @copyright Copyright (c) 2015 GearMagic Web-студия
 * @package Theme
 * @subpackage Impact
 * @since 1.0
 */

?>
<div class="container">
<div class="breadcrumbs">
    <?= $this->widget('gm.wd.breadcrumbs', ['navTag'=>'nav','navOptions'=>['aria-label'=>'breadcrumb',],'tag'=>'ol','options'=>['class'=>'breadcrumb',],'itemTemplate'=>'<li class="breadcrumb-item">{link}</li>','activeItemTemplate'=>'<li class="breadcrumb-item active">{link}</li>','ui'=>'bootstrap',]) ?>
</div>
</div>
        