<?php
/**
 * Подвал.
 * 
 * Часть макета страницы.
 * 
 * @author Anton Tivonenko <anton.tivonenko@gmail.com>
 * @copyright Copyright (c) 2015 GearMagic Web-студия
 * @package Theme
 * @subpackage Impact
 * @since 1.0
 */

?>
  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">

    <div class="container">
      <div class="row gy-4">
        <div class="col-lg-5 col-md-12 footer-info">
        <?= $this->beginMarkup('logo-footer', 'Логотип снизу') ?>
          <a href="/" class="logo d-flex align-items-center">
            <span>Импульс</span>
          </a>
          <?= $this->endMarkup() ?>
          <?= $this->beginMarkup('slogan-footer', 'Слоган снизу') ?>
          <p>Большая библиотека бизнес-аналитики и бизнес-процессов. Мы разрабатываем и внедряем бизнес-модели для различных организаций.</p>
          <?= $this->endMarkup() ?>
          <div class="social-links d-flex mt-4">
            <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
            <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
            <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
            <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
          </div>
        </div>

        <div class="col-lg-2 col-6 footer-links">
          <h4>Полезные ссылки</h4>
          <ul>
            <li><a href="/">Главная</a></li>
            <li><a href="/#about">О нас</a></li>
            <li><a href="/#services">Услуги</a></li>
            <li><a href="/sample-article.html">Условия обслуживания</a></li>
            <li><a href="/sample-article.html">Политика конфиденциальности</a></li>
          </ul>
        </div>

        <div class="col-lg-2 col-6 footer-links">
          <h4>Наши услуги</h4>
          <ul>
            <li><a href="/sample-article.html">Процессный офис</a></li>
            <li><a href="/sample-article.html">Моделированию бизнес-процессов</a></li>
            <li><a href="/sample-article.html">Диагностика системы управления организацией</a></li>
            <li><a href="/sample-article.html">Экспертно-методическое сопровождение проекта</a></li>
            <li><a href="/sample-article.html">Организация работы Процессного офиса</a></li>
            <li><a href="/sample-article.html">Проектирование Архитектуры бизнес-процессов</a></li>
          </ul>
        </div>

        <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
        <?= $this->beginMarkup('contacts-footer', 'Контакты снизу') ?>
          <h4>Свяжитесь с нами</h4>
          <p>
            ул. Московская <br>
            г. Москва<br>
            Россия <br><br>
            <strong>Телефон:</strong> +1 5589 55488 55<br>
            <strong>Email:</strong> info@example.com<br>
          </p>
        <?= $this->endMarkup() ?>
        </div>

      </div>
    </div>

    <div class="container mt-4">
      <div class="copyright">
      <?= $this->beginMarkup('copyright-footer', 'Авторские права снизу') ?>
        &copy; Copyright <strong><span>Импульс</span></strong>. Все права защищены
      <?= $this->endMarkup() ?>
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/impact-bootstrap-business-website-template/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>

  </footer><!-- End Footer -->
  <!-- End Footer -->

  <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <div id="preloader"></div>