<?php
/**
 * Список новостей.
 * Вызывает: 'pages/news'.
 * 
 * Часть макета страницы.
 * 
 * @author Anton Tivonenko <anton.tivonenko@gmail.com>
 * @copyright Copyright (c) 2015 GearMagic Web-студия
 * @package Theme
 * @subpackage Impact
 * @since 1.0
 * 
 * @var array $items
 * @var \Gm\View\Widget\ListView $widget
 */

if (empty($items)): ?>
    <div>Извините, эта страница не содержит записей. Попробуйте перейти по другой ссылке.</div>
<?php return; endif; ?>

<div class="row gy-4 posts-list">
<?php foreach ($items as $item): ?>
<!-- blog item -->
<div class="col-xl-4 col-md-6">
    <article>
        <div class="post-img">
            <img src="<?= $item['image'] ?: '/uploads/img/no-image.jpg' ?>" alt="" class="img-fluid">
        </div>
        <p class="post-category">Politics</p>
        <h2 class="title"><a href="<?= $item['url'] ?>"><?= $item['header'] ?></a></h2>
        <div class="d-flex align-items-center">
        <img src="/uploads/img/blog/blog-author.jpg" alt="" class="img-fluid post-author-img flex-shrink-0">
        <div class="post-meta">
            <p class="post-author-list">Maria Doe</p>
            <p class="post-date">
            <time datetime="<?= $item['date'] ?>"><?= Gm::$app->formatter->toDate($item['date'], 'long') ?></time>
            </p>
        </div>
        </div>
    </article>
</div>
<!-- /blog item -->
<?php endforeach ?>
</div>

<div class="blog-pagination">
    <?= $widget->renderPager() ?>
</div>