<?php
/**
 * Шапка.
 * 
 * Часть макета страницы.
 * 
 * @author Anton Tivonenko <anton.tivonenko@gmail.com>
 * @copyright Copyright (c) 2015 GearMagic Web-студия
 * @package Theme
 * @subpackage Impact
 * @since 1.0
 */

?>
<section id="topbar" class="topbar d-flex align-items-center">
<div class="container d-flex justify-content-center justify-content-md-between">
    <div class="contact-info d-flex align-items-center">
<?= $this->beginMarkup('contacts', 'Контакты сверху') ?>
    <i class="bi bi-envelope d-flex align-items-center"><a href="mailto:contact@example.com">contact@example.com</a></i>
    <i class="bi bi-phone d-flex align-items-center ms-4"><span>+1 5589 55488 55</span></i>
<?= $this->endMarkup() ?>
    </div>
    <div class="social-links d-none d-md-flex align-items-center">
<?= $this->beginMarkup('social', 'Соцсети сверху') ?>
    <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
    <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
    <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
    <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
<?= $this->endMarkup() ?>
    </div>
</div>
</section>
