<?php
/**
 * Макет главной страницы (по умолчанию).
 * 
 * @author Anton Tivonenko <anton.tivonenko@gmail.com>
 * @copyright Copyright (c) 2015 GearMagic Web-студия
 * @package Theme
 * @subpackage Impact
 * @since 1.0
 *
 * @var \Gm\View\LayoutView $this 
 * @var string $content
 */

$this->registerAsset('main');
?>
<!DOCTYPE HTML>
<html lang="<?= $this->getLang() ?>">
<head>
    <meta charset="<?= $this->getCharset() ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->head() ?>
</head>

<body>
    <?php $this->beginBody() ?>
    <?= $this->renderFrom('partials/topper') ?>

    <main id="main">
    <?= $content ?>
    </main>
    <!-- End #main -->

    <?= $this->renderFrom('partials/footer') ?>
    <?php $this->endBody() ?>
</body>

</html>
