    <!-- ======= About Us Section ======= -->
    <section id="about" class="about">
      <div class="container" data-aos="fade-up">

        <div class="section-header">
          <h2>About Us</h2>
          <p>Our team is the best professionals and industry experts in the field of business process management, building management systems, organizational development, training and employee engagement.</p>
        </div>

        <div class="row gy-4">
          <div class="col-lg-6">
            <h3>Process office outsourcing</h3>
            <img src="/uploads/img/about.jpg" class="img-fluid rounded-4 mb-4" alt="">
            <p>The business process management system is part of the overall management system.</p>
            <p>The main goal is to help managers make the company's business manageable and efficient, and increase the operational efficiency of the business.</p>
          </div>
          <div class="col-lg-6">
            <div class="content ps-0 ps-lg-5">
              <p class="fst-italic">
              Our team is united by common principles, goals, methods and experience in implementing consulting projects. Together we have gained a lot of experience working for the benefit of our clients. We use a network structure of the organization, assembling teams of professionals and industry experts for a specific project.
              </p>
              <ul>
                <li><i class="bi bi-check-circle-fill"></i> The officeless work model (laptop, professional software, knowledge base and Yandex disk) allows you to always be mobile.</li>
                <li><i class="bi bi-check-circle-fill"></i> We give preference to remote communications, but are always happy to have personal communication with the client in his office.</li>
              </ul>
              <p>
              We conduct trainings that are useful for managers and specialists who are tasked with carrying out projects for analyzing and optimizing the company's business processes.
              </p>

              <div class="position-relative mt-4">
                <img src="/uploads/img/about-2.jpg" class="img-fluid rounded-4" alt="">
                <a href="https://www.youtube.com/watch?v=LXb3EKWsInQ" class="glightbox play-btn"></a>
              </div>
            </div>
          </div>
        </div>

      </div>
    </section><!-- End About Us Section -->