    <!-- ======= Call To Action Section ======= -->
    <section id="call-to-action" class="call-to-action">
      <div class="container text-center" data-aos="zoom-out">
        <a href="https://www.youtube.com/watch?v=LXb3EKWsInQ" class="glightbox play-btn"></a>
        <h3>Выбери учебную программу</h3>
        <p> Мы предлагаем вашему набор учебных программ по тематике стратегического и процессного управления, моделированию процессов в бизнисе, работе с бизнес-архитектурой.</p>
        <a class="cta-btn" href="/sample-article.html">Просмотри</a>
      </div>
    </section><!-- End Call To Action Section -->