    <!-- ======= Call To Action Section ======= -->
    <section id="call-to-action" class="call-to-action">
      <div class="container text-center" data-aos="zoom-out">
        <a href="https://www.youtube.com/watch?v=LXb3EKWsInQ" class="glightbox play-btn"></a>
        <h3>Choose a curriculum</h3>
        <p>We offer you a set of training programs on the topics of strategic and process management, modeling business processes, and working with business architecture.</p>
        <a class="cta-btn" href="/sample-article.html">View</a>
      </div>
    </section><!-- End Call To Action Section -->