    <!-- ======= Frequently Asked Questions Section ======= -->
    <section id="faq" class="faq">
      <div class="container" data-aos="fade-up">

        <div class="row gy-4">

          <div class="col-lg-4">
            <div class="content px-xl-5">
              <h3>Frequently Asked <strong>Questions</strong></h3>
              <p>
              A collection of answers to the most common questions about business processes asked by employees of companies faced with a process approach.
              </p>
            </div>
          </div>

          <div class="col-lg-8">

            <div class="accordion accordion-flush" id="faqlist" data-aos="fade-up" data-aos-delay="100">

              <div class="accordion-item">
                <h3 class="accordion-header">
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faq-content-1">
                    <span class="num">1.</span>
                    What is a process approach?
                  </button>
                </h3>
                <div id="faq-content-1" class="accordion-collapse collapse" data-bs-parent="#faqlist">
                  <div class="accordion-body">
                  A management method that views an organization as a set of interconnected processes. Accordingly, the object of management, in this approach, is not functions, organizational units and specific people, but business processes. The process approach is characterized by a systematic solution to issues - not problems are eliminated, but the reasons for their occurrence.
                  </div>
                </div>
              </div><!-- # Faq item-->

              <div class="accordion-item">
                <h3 class="accordion-header">
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faq-content-2">
                    <span class="num">2.</span>
                    How is an operation different from a process?
                  </button>
                </h3>
                <div id="faq-content-2" class="accordion-collapse collapse" data-bs-parent="#faqlist">
                  <div class="accordion-body">
                  A business process is a set of actions or operations. An operation is an elementary action in a process that does not include other actions. The operation cannot be decomposed. At the same time, the author of the process model himself determines what is a process, and contains other processes and operations, and what does not need to be described in more detail, and, therefore, is an operation.
                  </div>
                </div>
              </div><!-- # Faq item-->

              <div class="accordion-item">
                <h3 class="accordion-header">
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faq-content-3">
                    <span class="num">3.</span>
                    What is the difference between a process and a subprocess?
                  </button>
                </h3>
                <div id="faq-content-3" class="accordion-collapse collapse" data-bs-parent="#faqlist">
                  <div class="accordion-body">
                  As a rule, all questions about business processes begin with this. In fact, the difference is small. A subprocess is usually called a process that, within the framework of the model under consideration, is part of another process. If a process can be divided into smaller processes, which, in turn, will contain an even more detailed description of actions, then these “smaller processes” are usually called subprocesses. Subprocesses can be broken down into subprocesses of the next level.
                  </div>
                </div>
              </div><!-- # Faq item-->

              <div class="accordion-item">
                <h3 class="accordion-header">
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faq-content-4">
                    <span class="num">4.</span>
                    What are the types of processes?
                  </button>
                </h3>
                <div id="faq-content-4" class="accordion-collapse collapse" data-bs-parent="#faqlist">
                  <div class="accordion-body">
                  It is customary to distinguish 3 main types: main business processes, auxiliary processes and management processes. 
                  </div>
                </div>
              </div><!-- # Faq item-->

              <div class="accordion-item">
                <h3 class="accordion-header">
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faq-content-5">
                    <span class="num">5.</span>
                    What is an end-to-end process?
                  </button>
                </h3>
                <div id="faq-content-5" class="accordion-collapse collapse" data-bs-parent="#faqlist">
                  <div class="accordion-body">
                  An end-to-end process is one that involves multiple organizational units. For example, the “Product Development” process will involve: Design Department, Marketing Department, Finance Department, Customer Service Department, and so on. The number of participating organizational units does not matter. If more than one department is involved in the process, it is already end-to-end.
                  </div>
                </div>
              </div><!-- # Faq item-->

            </div>

          </div>
        </div>

      </div>
    </section><!-- End Frequently Asked Questions Section -->