    <!-- ======= Frequently Asked Questions Section ======= -->
    <section id="faq" class="faq">
      <div class="container" data-aos="fade-up">

        <div class="row gy-4">

          <div class="col-lg-4">
            <div class="content px-xl-5">
              <h3>Часто задаваемые вопросы и <strong>Ответы</strong></h3>
              <p>
              Сборник ответов на наиболее распространенные вопросы по бизнес-процессам, которые задают сотрудники компаний, столкнувшихся с процессным подходом. 
              </p>
            </div>
          </div>

          <div class="col-lg-8">

            <div class="accordion accordion-flush" id="faqlist" data-aos="fade-up" data-aos-delay="100">

              <div class="accordion-item">
                <h3 class="accordion-header">
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faq-content-1">
                    <span class="num">1.</span>
                    Что такое процессный подход?
                  </button>
                </h3>
                <div id="faq-content-1" class="accordion-collapse collapse" data-bs-parent="#faqlist">
                  <div class="accordion-body">
                  Способ управления, который рассматривает организацию, как совокупность взаимосвязанных процессов. Соответственно, объектом управления, при данном подходе, являются не функции, организационные единицы и конкретные люди, а бизнес-процессы. Процессный подход отличается системным решением вопросов - устраняются не проблемы, а причины их возникновения.
                  </div>
                </div>
              </div><!-- # Faq item-->

              <div class="accordion-item">
                <h3 class="accordion-header">
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faq-content-2">
                    <span class="num">2.</span>
                    Чем операция отличается от процесса?
                  </button>
                </h3>
                <div id="faq-content-2" class="accordion-collapse collapse" data-bs-parent="#faqlist">
                  <div class="accordion-body">
                  Бизнес-процесс, это совокупность действий или операций. Операция - элементарное действие в процессе, которое не имеет в своем составе других действий. Операцию нельзя декомпозировать. При этом автор модели процесса сам определяет, что является процессом, и содержит в своем составе другие процессы и операции, а что не нужно описывать детальнее, и, поэтому, является операцией.
                  </div>
                </div>
              </div><!-- # Faq item-->

              <div class="accordion-item">
                <h3 class="accordion-header">
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faq-content-3">
                    <span class="num">3.</span>
                    В чем разница между процессом и подпроцессом?
                  </button>
                </h3>
                <div id="faq-content-3" class="accordion-collapse collapse" data-bs-parent="#faqlist">
                  <div class="accordion-body">
                  Как правило, с этого начинаются все вопросы по бизнес-процессам. На самом деле, разница небольшая. Подпроцессом принято называть процесс, который, в рамках рассматриваемой модели, находится в составе другого процесса. Если процесс можно разбить на более мелкие процессы, которые, в свою очередь будут содержать в себе еще более подробное описание действий, то эти «более мелкие процессы» принято называть подпроцессами. Подпроцессы могут разбиваться на подпроцессы следующего уровня.
                  </div>
                </div>
              </div><!-- # Faq item-->

              <div class="accordion-item">
                <h3 class="accordion-header">
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faq-content-4">
                    <span class="num">4.</span>
                    Какие бывают типы процессов?
                  </button>
                </h3>
                <div id="faq-content-4" class="accordion-collapse collapse" data-bs-parent="#faqlist">
                  <div class="accordion-body">
                  Принято выделять 3 основных типа: основные бизнес-процессы, вспомогательные процессы и процессы управления. 
                  </div>
                </div>
              </div><!-- # Faq item-->

              <div class="accordion-item">
                <h3 class="accordion-header">
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faq-content-5">
                    <span class="num">5.</span>
                    Что такое сквозной процесс?
                  </button>
                </h3>
                <div id="faq-content-5" class="accordion-collapse collapse" data-bs-parent="#faqlist">
                  <div class="accordion-body">
                  Сквозным является процесс, в котором участвуют несколько организационных единиц. К примеру, в процессе «Разработка продукта» будут участвовать: Конструкторский отдел, Отдел маркетинга, Финансовый отдел, Отдел обслуживания клиентов и так далее. Количество организационных единиц-участников не имеет значения. Если в процессе участвует больше одного отдела, он уже является сквозным.
                  </div>
                </div>
              </div><!-- # Faq item-->

            </div>

          </div>
        </div>

      </div>
    </section><!-- End Frequently Asked Questions Section -->