    <!-- ======= Portfolio Section ======= -->
    <section id="portfolio" class="portfolio sections-bg">
      <div class="container" data-aos="fade-up">

        <div class="section-header">
          <h2>Портфолио</h2>
          <p>Портфолио включает программное обеспечение для моделирования, анализа, регламентации и автоматизации бизнес-процессов, типовые решения, методические документы и т.д.</p>
        </div>

        <div class="portfolio-isotope" data-portfolio-filter="*" data-portfolio-layout="masonry" data-portfolio-sort="original-order" data-aos="fade-up" data-aos-delay="100">

          <div>
            <ul class="portfolio-flters">
              <li data-filter="*" class="filter-active">Все</li>
              <li data-filter=".filter-app">Приложения</li>
              <li data-filter=".filter-product">Товары</li>
              <li data-filter=".filter-branding">Бренды</li>
              <li data-filter=".filter-books">Книги</li>
            </ul><!-- End Portfolio Filters -->
          </div>

          <div class="row gy-4 portfolio-container">

            <div class="col-xl-4 col-md-6 portfolio-item filter-app">
              <div class="portfolio-wrap">
                <a href="/uploads/img/portfolio/app-1.jpg" data-gallery="portfolio-gallery-app" class="glightbox"><img src="/uploads/img/portfolio/app-1.jpg" class="img-fluid" alt=""></a>
                <div class="portfolio-info">
                  <h4><a href="/sample-article.html" title="Подробнее">Bizagi Process Modeler</a></h4>
                  <p>Бесплатное программное обеспечение для создания диаграмм процессов и документации в нотации стандарта BPMN.</p>
                </div>
              </div>
            </div><!-- End Portfolio Item -->

            <div class="col-xl-4 col-md-6 portfolio-item filter-product">
              <div class="portfolio-wrap">
                <a href="/uploads/img/portfolio/product-1.jpg" data-gallery="portfolio-gallery-app" class="glightbox"><img src="/uploads/img/portfolio/product-1.jpg" class="img-fluid" alt=""></a>
                <div class="portfolio-info">
                  <h4><a href="/sample-article.html" title="Подробнее">ELMA BPM</a></h4>
                  <p>Система управления бизнес-процессами ELMA BPM.</p>
                </div>
              </div>
            </div><!-- End Portfolio Item -->

            <div class="col-xl-4 col-md-6 portfolio-item filter-branding">
              <div class="portfolio-wrap">
                <a href="/uploads/img/portfolio/branding-1.jpg" data-gallery="portfolio-gallery-app" class="glightbox"><img src="/uploads/img/portfolio/branding-1.jpg" class="img-fluid" alt=""></a>
                <div class="portfolio-info">
                  <h4><a href="/sample-article.html" title="Подробнее">IBM WebSphere Business Modeler</a></h4>
                  <p>IBM WebSphere Business Modeler является программным средством, нацеленным на моделирование, имитацию и анализ бизнес-процессов.</p>
                </div>
              </div>
            </div><!-- End Portfolio Item -->

            <div class="col-xl-4 col-md-6 portfolio-item filter-books">
              <div class="portfolio-wrap">
                <a href="/uploads/img/portfolio/books-1.jpg" data-gallery="portfolio-gallery-app" class="glightbox"><img src="/uploads/img/portfolio/books-1.jpg" class="img-fluid" alt=""></a>
                <div class="portfolio-info">
                  <h4><a href="/sample-article.html" title="Подробнее">Критическая цепь. Элия Голдратт.</a></h4>
                  <p>Метод оценки и планирования работ, проектов, в основе которого лежит понимание взаимосвязи задач и ресурсов, а также влияние рисков на весь проект или работы.</p>
                </div>
              </div>
            </div><!-- End Portfolio Item -->

            <div class="col-xl-4 col-md-6 portfolio-item filter-app">
              <div class="portfolio-wrap">
                <a href="/uploads/img/portfolio/app-2.jpg" data-gallery="portfolio-gallery-app" class="glightbox"><img src="/uploads/img/portfolio/app-2.jpg" class="img-fluid" alt=""></a>
                <div class="portfolio-info">
                  <h4><a href="/sample-article.html" title="Подробнее">Intalio BPMS</a></h4>
                  <p>Бесплатная. Open Source Business Management System. Программа для построения и анализа бизнес процессов.</p>
                </div>
              </div>
            </div><!-- End Portfolio Item -->

            <div class="col-xl-4 col-md-6 portfolio-item filter-product">
              <div class="portfolio-wrap">
                <a href="/uploads/img/portfolio/product-2.jpg" data-gallery="portfolio-gallery-app" class="glightbox"><img src="/uploads/img/portfolio/product-2.jpg" class="img-fluid" alt=""></a>
                <div class="portfolio-info">
                  <h4><a href="/sample-article.html" title="Подробнее">Первая форма</a></h4>
                  <p>Автоматизация задач, организация единого информационного пространства, выстроить внутренние коммуникации, обеспечить максимальную кибербезопасность и защиту данных.</p>
                </div>
              </div>
            </div><!-- End Portfolio Item -->

            <div class="col-xl-4 col-md-6 portfolio-item filter-branding">
              <div class="portfolio-wrap">
                <a href="/uploads/img/portfolio/branding-2.jpg" data-gallery="portfolio-gallery-app" class="glightbox"><img src="/uploads/img/portfolio/branding-2.jpg" class="img-fluid" alt=""></a>
                <div class="portfolio-info">
                  <h4><a href="/sample-article.html" title="Подробнее">AllFusion Process Modeler</a></h4>
                  <p>Описание, анализ и моделирование модели данных, построитель мета-моделей данных.</p>
                </div>
              </div>
            </div><!-- End Portfolio Item -->

            <div class="col-xl-4 col-md-6 portfolio-item filter-books">
              <div class="portfolio-wrap">
                <a href="/uploads/img/portfolio/books-2.jpg" data-gallery="portfolio-gallery-app" class="glightbox"><img src="/uploads/img/portfolio/books-2.jpg" class="img-fluid" alt=""></a>
                <div class="portfolio-info">
                  <h4><a href="/sample-article.html" title="Подробнее">Учитесь видеть бизнес процессы</a></h4>
                  <p>Построение карт потоков создания ценности. М.Ротер., Д.Шук.</p>
                </div>
              </div>
            </div><!-- End Portfolio Item -->

            <div class="col-xl-4 col-md-6 portfolio-item filter-app">
              <div class="portfolio-wrap">
                <a href="/uploads/img/portfolio/app-3.jpg" data-gallery="portfolio-gallery-app" class="glightbox"><img src="/uploads/img/portfolio/app-3.jpg" class="img-fluid" alt=""></a>
                <div class="portfolio-info">
                  <h4><a href="/sample-article.html" title="Подробнее">ARIS Express</a></h4>
                  <p>Достаточно простой в установке и использовании инструмент, так что его могут применять и начинающие пользователи.</p>
                </div>
              </div>
            </div><!-- End Portfolio Item -->

            <div class="col-xl-4 col-md-6 portfolio-item filter-product">
              <div class="portfolio-wrap">
                <a href="/uploads/img/portfolio/product-3.jpg" data-gallery="portfolio-gallery-app" class="glightbox"><img src="/uploads/img/portfolio/product-3.jpg" class="img-fluid" alt=""></a>
                <div class="portfolio-info">
                  <h4><a href="/sample-article.html" title="Подробнее">LeaderTask</a></h4>
                  <p>Сервис позволяет выстроить эффективный тайм-менеджмент и создать единую информационную базу компании.</p>
                </div>
              </div>
            </div><!-- End Portfolio Item -->

            <div class="col-xl-4 col-md-6 portfolio-item filter-branding">
              <div class="portfolio-wrap">
                <a href="/uploads/img/portfolio/branding-3.jpg" data-gallery="portfolio-gallery-app" class="glightbox"><img src="/uploads/img/portfolio/branding-3.jpg" class="img-fluid" alt=""></a>
                <div class="portfolio-info">
                  <h4><a href="/sample-article.html" title="Подробнее">Camunda</a></h4>
                  <p>BPM-движок для автоматизации бизнес-процессов.</p>
                </div>
              </div>
            </div><!-- End Portfolio Item -->

            <div class="col-xl-4 col-md-6 portfolio-item filter-books">
              <div class="portfolio-wrap">
                <a href="/uploads/img/portfolio/books-3.jpg" data-gallery="portfolio-gallery-app" class="glightbox"><img src="/uploads/img/portfolio/books-3.jpg" class="img-fluid" alt=""></a>
                <div class="portfolio-info">
                  <h4><a href="/sample-article.html" title="Подробнее">Управление бизнес-процессами</a></h4>
                  <p>Практическое руководство по реализации проектов. Д.Джестон., Й.Нелис</p>
                </div>
              </div>
            </div><!-- End Portfolio Item -->

          </div><!-- End Portfolio Container -->

        </div>

      </div>
    </section><!-- End Portfolio Section -->