    <!-- ======= Portfolio Section ======= -->
    <section id="portfolio" class="portfolio sections-bg">
      <div class="container" data-aos="fade-up">

        <div class="section-header">
          <h2>Portfolio</h2>
          <p>The portfolio includes software for modeling, analysis, regulation and automation of business processes, standard solutions, methodological documents, etc.</p>
        </div>

        <div class="portfolio-isotope" data-portfolio-filter="*" data-portfolio-layout="masonry" data-portfolio-sort="original-order" data-aos="fade-up" data-aos-delay="100">

          <div>
            <ul class="portfolio-flters">
              <li data-filter="*" class="filter-active">All</li>
              <li data-filter=".filter-app">Applications</li>
              <li data-filter=".filter-product">Goods</li>
              <li data-filter=".filter-branding">Brands</li>
              <li data-filter=".filter-books">Books</li>
            </ul><!-- End Portfolio Filters -->
          </div>

          <div class="row gy-4 portfolio-container">

            <div class="col-xl-4 col-md-6 portfolio-item filter-app">
              <div class="portfolio-wrap">
                <a href="/uploads/img/portfolio/app-1.jpg" data-gallery="portfolio-gallery-app" class="glightbox"><img src="/uploads/img/portfolio/app-1.jpg" class="img-fluid" alt=""></a>
                <div class="portfolio-info">
                  <h4><a href="/sample-article.html" title="More Details">Bizagi Process Modeler</a></h4>
                  <p>Free software for creating process diagrams and documentation in BPMN standard notation.</p>
                </div>
              </div>
            </div><!-- End Portfolio Item -->

            <div class="col-xl-4 col-md-6 portfolio-item filter-product">
              <div class="portfolio-wrap">
                <a href="/uploads/img/portfolio/product-1.jpg" data-gallery="portfolio-gallery-app" class="glightbox"><img src="/uploads/img/portfolio/product-1.jpg" class="img-fluid" alt=""></a>
                <div class="portfolio-info">
                  <h4><a href="/sample-article.html" title="More Details">ELMA BPM</a></h4>
                  <p>Business process management system ELMA BPM.</p>
                </div>
              </div>
            </div><!-- End Portfolio Item -->

            <div class="col-xl-4 col-md-6 portfolio-item filter-branding">
              <div class="portfolio-wrap">
                <a href="/uploads/img/portfolio/branding-1.jpg" data-gallery="portfolio-gallery-app" class="glightbox"><img src="/uploads/img/portfolio/branding-1.jpg" class="img-fluid" alt=""></a>
                <div class="portfolio-info">
                  <h4><a href="/sample-article.html" title="More Details">IBM WebSphere Business Modeler</a></h4>
                  <p>IBM WebSphere Business Modeler is a software tool aimed at modeling, simulating and analyzing business processes.</p>
                </div>
              </div>
            </div><!-- End Portfolio Item -->

            <div class="col-xl-4 col-md-6 portfolio-item filter-books">
              <div class="portfolio-wrap">
                <a href="/uploads/img/portfolio/books-1.jpg" data-gallery="portfolio-gallery-app" class="glightbox"><img src="/uploads/img/portfolio/books-1.jpg" class="img-fluid" alt=""></a>
                <div class="portfolio-info">
                  <h4><a href="/sample-article.html" title="More Details">Critical chain. Elia Goldratt.</a></h4>
                  <p>A method for assessing and planning work and projects, which is based on an understanding of the relationship between tasks and resources, as well as the impact of risks on the entire project or work.</p>
                </div>
              </div>
            </div><!-- End Portfolio Item -->

            <div class="col-xl-4 col-md-6 portfolio-item filter-app">
              <div class="portfolio-wrap">
                <a href="/uploads/img/portfolio/app-2.jpg" data-gallery="portfolio-gallery-app" class="glightbox"><img src="/uploads/img/portfolio/app-2.jpg" class="img-fluid" alt=""></a>
                <div class="portfolio-info">
                  <h4><a href="/sample-article.html" title="More Details">Intalio BPMS</a></h4>
                  <p>Free. Open Source Business Management System. A program for building and analyzing business processes.</p>
                </div>
              </div>
            </div><!-- End Portfolio Item -->

            <div class="col-xl-4 col-md-6 portfolio-item filter-product">
              <div class="portfolio-wrap">
                <a href="/uploads/img/portfolio/product-2.jpg" data-gallery="portfolio-gallery-app" class="glightbox"><img src="/uploads/img/portfolio/product-2.jpg" class="img-fluid" alt=""></a>
                <div class="portfolio-info">
                  <h4><a href="/sample-article.html" title="More Details">First form</a></h4>
                  <p>Automate tasks, organize a single information space, build internal communications, ensure maximum cybersecurity and data protection.</p>
                </div>
              </div>
            </div><!-- End Portfolio Item -->

            <div class="col-xl-4 col-md-6 portfolio-item filter-branding">
              <div class="portfolio-wrap">
                <a href="/uploads/img/portfolio/branding-2.jpg" data-gallery="portfolio-gallery-app" class="glightbox"><img src="/uploads/img/portfolio/branding-2.jpg" class="img-fluid" alt=""></a>
                <div class="portfolio-info">
                  <h4><a href="/sample-article.html" title="More Details">AllFusion Process Modeler</a></h4>
                  <p>Description, analysis and modeling of data models, builder of meta-data models.</p>
                </div>
              </div>
            </div><!-- End Portfolio Item -->

            <div class="col-xl-4 col-md-6 portfolio-item filter-books">
              <div class="portfolio-wrap">
                <a href="/uploads/img/portfolio/books-2.jpg" data-gallery="portfolio-gallery-app" class="glightbox"><img src="/uploads/img/portfolio/books-2.jpg" class="img-fluid" alt=""></a>
                <div class="portfolio-info">
                  <h4><a href="/sample-article.html" title="More Details">Learn to see business processes</a></h4>
                  <p>Constructing value stream maps. M. Rother., D. Shook.</p>
                </div>
              </div>
            </div><!-- End Portfolio Item -->

            <div class="col-xl-4 col-md-6 portfolio-item filter-app">
              <div class="portfolio-wrap">
                <a href="/uploads/img/portfolio/app-3.jpg" data-gallery="portfolio-gallery-app" class="glightbox"><img src="/uploads/img/portfolio/app-3.jpg" class="img-fluid" alt=""></a>
                <div class="portfolio-info">
                  <h4><a href="/sample-article.html" title="More Details">ARIS Express</a></h4>
                  <p>The tool is quite easy to install and use, so that even novice users can use it.</p>
                </div>
              </div>
            </div><!-- End Portfolio Item -->

            <div class="col-xl-4 col-md-6 portfolio-item filter-product">
              <div class="portfolio-wrap">
                <a href="/uploads/img/portfolio/product-3.jpg" data-gallery="portfolio-gallery-app" class="glightbox"><img src="/uploads/img/portfolio/product-3.jpg" class="img-fluid" alt=""></a>
                <div class="portfolio-info">
                  <h4><a href="/sample-article.html" title="More Details">LeaderTask</a></h4>
                  <p>The service allows you to build effective time management and create a unified information base for the company.</p>
                </div>
              </div>
            </div><!-- End Portfolio Item -->

            <div class="col-xl-4 col-md-6 portfolio-item filter-branding">
              <div class="portfolio-wrap">
                <a href="/uploads/img/portfolio/branding-3.jpg" data-gallery="portfolio-gallery-app" class="glightbox"><img src="/uploads/img/portfolio/branding-3.jpg" class="img-fluid" alt=""></a>
                <div class="portfolio-info">
                  <h4><a href="/sample-article.html" title="More Details">Camunda</a></h4>
                  <p>BPM engine for automating business processes.</p>
                </div>
              </div>
            </div><!-- End Portfolio Item -->

            <div class="col-xl-4 col-md-6 portfolio-item filter-books">
              <div class="portfolio-wrap">
                <a href="/uploads/img/portfolio/books-3.jpg" data-gallery="portfolio-gallery-app" class="glightbox"><img src="/uploads/img/portfolio/books-3.jpg" class="img-fluid" alt=""></a>
                <div class="portfolio-info">
                  <h4><a href="/sample-article.html" title="More Details">Business process management</a></h4>
                  <p>Practical guide to project implementation. D. Jeston, J. Nelis</p>
                </div>
              </div>
            </div><!-- End Portfolio Item -->

          </div><!-- End Portfolio Container -->

        </div>

      </div>
    </section><!-- End Portfolio Section -->