    <!-- ======= Pricing Section ======= -->
    <section id="pricing" class="pricing sections-bg">
      <div class="container" data-aos="fade-up">

        <div class="section-header">
          <h2>Pricing</h2>
          <p>We have selected the most popular integration options</p>
        </div>

        <div class="row g-4 py-lg-5" data-aos="zoom-out" data-aos-delay="100">

          <div class="col-lg-4">
            <div class="pricing-item">
              <h3>Start</h3>
              <div class="icon">
                <i class="bi bi-box"></i>
              </div>
              <h4>5000<sup>rub</sup><span> / per month</span></h4>
              <ul>
                <li><i class="bi bi-check"></i> Business analysis of the company</li>
                <li><i class="bi bi-check"></i> Building a sales funnel</li>
                <li><i class="bi bi-check"></i> Creation of business automation processes</li>
                <li class="na"><i class="bi bi-x"></i> <span>Three meetings with a business analyst</span></li>
              </ul>
              <div class="text-center"><a href="/sample-article.html" class="buy-btn">Order</a></div>
            </div>
          </div><!-- End Pricing Item -->

          <div class="col-lg-4">
            <div class="pricing-item featured">
              <h3>Base</h3>
              <div class="icon">
                <i class="bi bi-airplane"></i>
              </div>

              <h4>12000<sup>rub</sup><span> / per month</span></h4>
              <ul>
                <li><i class="bi bi-check"></i> Service integration</li>
                <li><i class="bi bi-check"></i> Training</li>
                <li><i class="bi bi-check"></i> Development of 2 solutions is included in the price of the tariff</li>
                <li><i class="bi bi-check"></i> Business analysis of the company</li>
                <li><i class="bi bi-check"></i> Building a sales funnel</li>
              </ul>
              <div class="text-center"><a href="/sample-article.html" class="buy-btn">Order</a></div>
            </div>
          </div><!-- End Pricing Item -->

          <div class="col-lg-4">
            <div class="pricing-item">
              <h3>Maximum</h3>
              <div class="icon">
                <i class="bi bi-send"></i>
              </div>
              <h4>30000<sup>rub</sup><span> / per month</span></h4>
              <ul>
                <li><i class="bi bi-check"></i> Service integration</li>
                <li><i class="bi bi-check"></i> Training</li>
                <li><i class="bi bi-check"></i> Business analysis of the company</li>
                <li><i class="bi bi-check"></i> Building a sales funnel</li>
                <li><i class="bi bi-check"></i> Creation of business automation processes</li>
              </ul>
              <div class="text-center"><a href="/sample-article.html" class="buy-btn">Order</a></div>
            </div>
          </div><!-- End Pricing Item -->

        </div>

      </div>
    </section><!-- End Pricing Section -->