    <!-- ======= Pricing Section ======= -->
    <section id="pricing" class="pricing sections-bg">
      <div class="container" data-aos="fade-up">

        <div class="section-header">
          <h2>Стоимость</h2>
          <p>Мы подбрали самые популярные варианты интеграции</p>
        </div>

        <div class="row g-4 py-lg-5" data-aos="zoom-out" data-aos-delay="100">

          <div class="col-lg-4">
            <div class="pricing-item">
              <h3>Стартовый</h3>
              <div class="icon">
                <i class="bi bi-box"></i>
              </div>
              <h4>5000<sup>руб</sup><span> / в месяц</span></h4>
              <ul>
                <li><i class="bi bi-check"></i> Бизнес анализ компании</li>
                <li><i class="bi bi-check"></i> Построение воронки продаж</li>
                <li><i class="bi bi-check"></i> Создание бизнес процессов автоматизации</li>
                <li class="na"><i class="bi bi-x"></i> <span>Три встречи с бизнес аналитоком</span></li>
              </ul>
              <div class="text-center"><a href="/sample-article.html" class="buy-btn">Заказать</a></div>
            </div>
          </div><!-- End Pricing Item -->

          <div class="col-lg-4">
            <div class="pricing-item featured">
              <h3>Базовый</h3>
              <div class="icon">
                <i class="bi bi-airplane"></i>
              </div>

              <h4>12000<sup>руб</sup><span> / в месяц</span></h4>
              <ul>
                <li><i class="bi bi-check"></i> Интеграция сервисов</li>
                <li><i class="bi bi-check"></i> Обучение персонала</li>
                <li><i class="bi bi-check"></i> Разработка 2 решений входит в стоимость тарифа</li>
                <li><i class="bi bi-check"></i> Бизнес анализ компании</li>
                <li><i class="bi bi-check"></i> Построение воронки продаж</li>
              </ul>
              <div class="text-center"><a href="/sample-article.html" class="buy-btn">Заказать</a></div>
            </div>
          </div><!-- End Pricing Item -->

          <div class="col-lg-4">
            <div class="pricing-item">
              <h3>Максимальный</h3>
              <div class="icon">
                <i class="bi bi-send"></i>
              </div>
              <h4>30000<sup>руб</sup><span> / в месяц</span></h4>
              <ul>
                <li><i class="bi bi-check"></i> Интеграция сервисов</li>
                <li><i class="bi bi-check"></i> Обучение персонала</li>
                <li><i class="bi bi-check"></i> Бизнес анализ компании</li>
                <li><i class="bi bi-check"></i> Построение воронки продаж</li>
                <li><i class="bi bi-check"></i> Cоздание бизнес процессов автоматизации</li>
              </ul>
              <div class="text-center"><a href="/sample-article.html" class="buy-btn">Заказать</a></div>
            </div>
          </div><!-- End Pricing Item -->

        </div>

      </div>
    </section><!-- End Pricing Section -->