
    <!-- ======= Recent Blog Posts Section ======= -->
    <section id="recent-posts" class="recent-posts sections-bg">
      <div class="container" data-aos="fade-up">

        <div class="section-header">
          <h2>Последние сообщения в блоге / <a href="/news">все сообщения</a></h2>
        </div>

        <div class="row gy-4">

          <div class="col-xl-4 col-md-6">
            <article>

              <div class="post-img">
                <img src="/uploads/img/blog/blog-1.jpg" alt="" class="img-fluid">
              </div>

              <p class="post-category">Аналитика</p>

              <h2 class="title">
                <a href="/sample-article.html">Виды бизнес-процессов</a>
              </h2>

              <div class="d-flex align-items-center">
                <img src="/uploads/img/blog/blog-author.jpg" alt="" class="img-fluid post-author-img flex-shrink-0">
                <div class="post-meta">
                  <p class="post-author">Мария До</p>
                  <p class="post-date">
                    <time datetime="2024-01-01">Jan 1, 2024</time>
                  </p>
                </div>
              </div>

            </article>
          </div><!-- End post list item -->

          <div class="col-xl-4 col-md-6">
            <article>

              <div class="post-img">
                <img src="/uploads/img/blog/blog-2.jpg" alt="" class="img-fluid">
              </div>

              <p class="post-category">Аналитика</p>

              <h2 class="title">
                <a href="/sample-article.html">Эффективность процессного подхода</a>
              </h2>

              <div class="d-flex align-items-center">
                <img src="/uploads/img/blog/blog-author-2.jpg" alt="" class="img-fluid post-author-img flex-shrink-0">
                <div class="post-meta">
                  <p class="post-author">Аллиса Майер</p>
                  <p class="post-date">
                    <time datetime="2024-01-01">Jun 5, 2024</time>
                  </p>
                </div>
              </div>

            </article>
          </div><!-- End post list item -->

          <div class="col-xl-4 col-md-6">
            <article>

              <div class="post-img">
                <img src="/uploads/img/blog/blog-3.jpg" alt="" class="img-fluid">
              </div>

              <p class="post-category">Управление</p>

              <h2 class="title">
                <a href="/sample-article.html">Система менеджмента качества</a>
              </h2>

              <div class="d-flex align-items-center">
                <img src="/uploads/img/blog/blog-author-3.jpg" alt="" class="img-fluid post-author-img flex-shrink-0">
                <div class="post-meta">
                  <p class="post-author">Марк Дауэр</p>
                  <p class="post-date">
                    <time datetime="2024-01-01">Jun 22, 2024</time>
                  </p>
                </div>
              </div>

            </article>
          </div><!-- End post list item -->

        </div><!-- End recent posts list -->

      </div>
    </section><!-- End Recent Blog Posts Section -->