    <!-- ======= Our Services Section ======= -->
    <section id="services" class="services sections-bg">
      <div class="container" data-aos="fade-up">

        <div class="section-header">
          <h2>Our Services</h2>
          <p>We offer software for modeling, analysis, regulation and automation of business processes, standard solutions, methodological documents, etc.</p>
        </div>

        <div class="row gy-4" data-aos="fade-up" data-aos-delay="100">

          <div class="col-lg-4 col-md-6">
            <div class="service-item  position-relative">
              <div class="icon">
                <i class="bi bi-activity"></i>
              </div>
              <h3>Process office</h3>
              <p>To create and purposefully develop a Business Process Management System, a special functional unit is created in the organization - the Process Office.</p>
              <a href="/sample-article.html" class="readmore stretched-link">Read more <i class="bi bi-arrow-right"></i></a>
            </div>
          </div><!-- End Service Item -->

          <div class="col-lg-4 col-md-6">
            <div class="service-item position-relative">
              <div class="icon">
                <i class="bi bi-broadcast"></i>
              </div>
              <h3>Business process modeling</h3>
              <p>Implementation and methodological support for modeling business processes in your architecture.</p>
              <a href="/sample-article.html" class="readmore stretched-link">Read more <i class="bi bi-arrow-right"></i></a>
            </div>
          </div><!-- End Service Item -->

          <div class="col-lg-4 col-md-6">
            <div class="service-item position-relative">
              <div class="icon">
                <i class="bi bi-easel"></i>
              </div>
              <h3>Diagnostics of the organization's management system</h3>
              <p>Our team has accumulated extensive experience in diagnosing organizational management systems.</p>
              <a href="/sample-article.html" class="readmore stretched-link">Read more <i class="bi bi-arrow-right"></i></a>
            </div>
          </div><!-- End Service Item -->

          <div class="col-lg-4 col-md-6">
            <div class="service-item position-relative">
              <div class="icon">
                <i class="bi bi-bounding-box-circles"></i>
              </div>
              <h3>Expert and methodological support of the project</h3>
              <p>Expert and methodological support for your project: analysis of the quality of graphic diagrams, analysis of the architecture of business processes, etc.</p>
              <a href="/sample-article.html" class="readmore stretched-link">Read more <i class="bi bi-arrow-right"></i></a>
            </div>
          </div><!-- End Service Item -->

          <div class="col-lg-4 col-md-6">
            <div class="service-item position-relative">
              <div class="icon">
                <i class="bi bi-calendar4-week"></i>
              </div>
              <h3>Organization of the Process Office work</h3>
              <p>Organization of a functional division of a company with a number of special competencies in the field of process management.</p>
              <a href="/sample-article.html" class="readmore stretched-link">Read more <i class="bi bi-arrow-right"></i></a>
            </div>
          </div><!-- End Service Item -->

          <div class="col-lg-4 col-md-6">
            <div class="service-item position-relative">
              <div class="icon">
                <i class="bi bi-chat-square-text"></i>
              </div>
              <h3>Business Process Architecture Design</h3>
              <p>Introduction of modern process management technologies.</p>
              <a href="/sample-article.html" class="readmore stretched-link">Read more <i class="bi bi-arrow-right"></i></a>
            </div>
          </div><!-- End Service Item -->

        </div>

      </div>
    </section><!-- End Our Services Section -->