    <!-- ======= Our Services Section ======= -->
    <section id="services" class="services sections-bg">
      <div class="container" data-aos="fade-up">

        <div class="section-header">
          <h2>Наши услуги</h2>
          <p>Мы предлагаем программное обеспечение для моделирования, анализа, регламентации и автоматизации бизнес-процессов, типовые решения, методические документы и т.п.</p>
        </div>

        <div class="row gy-4" data-aos="fade-up" data-aos-delay="100">

          <div class="col-lg-4 col-md-6">
            <div class="service-item  position-relative">
              <div class="icon">
                <i class="bi bi-activity"></i>
              </div>
              <h3>Процессный офис</h3>
              <p>Для создания и целенаправленного развития Системы управления бизнес-процессами в организации создается специальное функциональное подразделение — Процессный офис.</p>
              <a href="/sample-article.html" class="readmore stretched-link">Подробнее <i class="bi bi-arrow-right"></i></a>
            </div>
          </div><!-- End Service Item -->

          <div class="col-lg-4 col-md-6">
            <div class="service-item position-relative">
              <div class="icon">
                <i class="bi bi-broadcast"></i>
              </div>
              <h3>Моделированию бизнес-процессов</h3>
              <p>Выполнение и методическое сопровождения для моделирования бизнес-процессов в вашей архитектуре.</p>
              <a href="/sample-article.html" class="readmore stretched-link">Подробнее <i class="bi bi-arrow-right"></i></a>
            </div>
          </div><!-- End Service Item -->

          <div class="col-lg-4 col-md-6">
            <div class="service-item position-relative">
              <div class="icon">
                <i class="bi bi-easel"></i>
              </div>
              <h3>Диагностика системы управления организацией</h3>
              <p>Наша команда накопила большой опыт проведения диагностики систем управления организациями.</p>
              <a href="/sample-article.html" class="readmore stretched-link">Подробнее <i class="bi bi-arrow-right"></i></a>
            </div>
          </div><!-- End Service Item -->

          <div class="col-lg-4 col-md-6">
            <div class="service-item position-relative">
              <div class="icon">
                <i class="bi bi-bounding-box-circles"></i>
              </div>
              <h3>Экспертно-методическое сопровождение проекта</h3>
              <p>Экспертно-методическое сопровождение вашего проекта: анализ качества графических схем, анализ архитектуры бизнес-процессов, и т.д.</p>
              <a href="/sample-article.html" class="readmore stretched-link">Подробнее <i class="bi bi-arrow-right"></i></a>
            </div>
          </div><!-- End Service Item -->

          <div class="col-lg-4 col-md-6">
            <div class="service-item position-relative">
              <div class="icon">
                <i class="bi bi-calendar4-week"></i>
              </div>
              <h3>Организация работы Процессного офиса</h3>
              <p>Организация функционального подразделения компании, обладающее рядом специальных компетенций в области процессного управления.</p>
              <a href="/sample-article.html" class="readmore stretched-link">Подробнее <i class="bi bi-arrow-right"></i></a>
            </div>
          </div><!-- End Service Item -->

          <div class="col-lg-4 col-md-6">
            <div class="service-item position-relative">
              <div class="icon">
                <i class="bi bi-chat-square-text"></i>
              </div>
              <h3>Проектирование Архитектуры бизнес-процессов</h3>
              <p>Внедрение современных технологий процессного управления.</p>
              <a href="/sample-article.html" class="readmore stretched-link">Подробнее <i class="bi bi-arrow-right"></i></a>
            </div>
          </div><!-- End Service Item -->

        </div>

      </div>
    </section><!-- End Our Services Section -->