<?php
/**
 * Шаблон ошибки 404 (Not Found).
 * 
 * @author Anton Tivonenko <anton.tivonenko@gmail.com>
 * @copyright Copyright (c) 2015 GearMagic Web-студия
 * @package Theme
 * @subpackage Impact
 * @since 1.0
 */
?>
<!DOCTYPE HTML>
<html lang="ru-RU">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Ошибка 404 (Не найдено)</title>
    <link type="image/png" href="<?= Gm::getAlias('@theme::/assets/ico/favicon.ico') ?>" rel="icon" sizes="16x16">
    <link rel="stylesheet" href="<?= Gm::getAlias('@theme::/vendors/bootstrap/css/bootstrap.min.css') ?>" />
    <link rel="stylesheet" href="<?= Gm::getAlias('@theme::/assets/css/main.css') ?>" />
</head>

<body>
    <section class="blog">
        <div class="container aos-init aos-animate" data-aos="fade-up">
            <div class="row g-5">
                <div class="col-lg-12">
                    <article class="blog-details">
                        <h2 class="title">Ошибка 404 (Не найдено)</h2>
                        <div class="content">
                            <p>Вы пытаетесь получить доступ к странице, которая возможно была удалена.</p>
                            <ol>
                                <li>Проверьте корректность вводимого вами адреса и/или скорректируйте его.</li>
                                <li>Очистите кэш вашего браузера и попробуйте обратиться к странице вновь.</li>
                                <li>Перейдите на главную страницу сайта и попробуйте найти нужную информацию, переходя по ссылкам.</li>
                                <li>Поищите страницу в поисковых системах — возможно страница была опубликована по новому адресу.</li>
                            </ol>
                        </div>
                    </article>
                </div>
            </div>
        </div>
    </section>
</body>

</html>