<?php
/**
 * Шаблон ошибки подключения к базе данных.
 * 
 * @author Anton Tivonenko <anton.tivonenko@gmail.com>
 * @copyright Copyright (c) 2015 GearMagic Web-студия
 * @package Theme
 * @subpackage Impact
 * @since 1.0
 */
?>
<!DOCTYPE HTML>
<html lang="en-GB">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>IP address is Blocked</title>
    <link type="image/png" href="<?= Gm::getAlias('@theme::/assets/ico/favicon.ico') ?>" rel="icon" sizes="16x16">
    <link rel="stylesheet" href="<?= Gm::getAlias('@theme::/vendors/bootstrap/css/bootstrap.min.css') ?>" />
    <link rel="stylesheet" href="<?= Gm::getAlias('@theme::/assets/css/main.css') ?>" />
</head>

<body>
    <section class="blog">
        <div class="container aos-init aos-animate" data-aos="fade-up">
            <div class="row g-5">
                <div class="col-lg-12">
                    <article class="blog-details">
                        <h2 class="title">IP address is Blocked</h2>
                        <div class="content">
                            <p><?= $exception->getDispatch() ?></p>
                        </div>
                    </article>
                </div>
            </div>
        </div>
    </section>
</body>

</html>