<?php
/**
 * Ошибка 403 (Forbidden en_GB).
 * 
 * Шаблон страницы.
 * 
 * @author Anton Tivonenko <anton.tivonenko@gmail.com>
 * @copyright Copyright (c) 2015 GearMagic Web-студия
 * @package Theme
 * @subpackage Impact
 * @since 1.0
 */

$this->title('Error 403 (Forbidden)');
?>
<section class="blog">
    <div class="container aos-init aos-animate" data-aos="fade-up">
        <div class="row g-5">
            <div class="col-lg-12">
                <article class="blog-details">
                    <h2 class="title">Error 403 (Forbidden)</h2>
                    <div class="content">
                        <p>Access to this page is denied.</p>
                        <ol>
                            <li>Double click on the URL in the address bar of the browser, you may have entered the page address incorrectly.</li>
                            <li>Clear your browser's cache. The cached version of the page you were trying to visit could be causing the error. </li>
                            <li>Try to login again. </li>
                        </ol>
                    </div>
                </article>
            </div>
        </div>
    </div>
</section>