<?php
/**
 * Ошибка 403 (Forbidden).
 * 
 * Шаблон страницы.
 * 
 * @author Anton Tivonenko <anton.tivonenko@gmail.com>
 * @copyright Copyright (c) 2015 GearMagic Web-студия
 * @package Theme
 * @subpackage Impact
 * @since 1.0
 */

$this->title('Ошибка 403 (Запрещено)');
?>
<section class="blog">
    <div class="container aos-init aos-animate" data-aos="fade-up">
        <div class="row g-5">
            <div class="col-lg-12">
                <article class="blog-details">
                    <h2 class="title">Ошибка 403 (Запрещено)</h2>
                    <div class="content">
                        <p>Доступ к данной странице запрещен.</p>
                        <h3>Что нужно сделать:</h3>
                        <ol>
                            <li>Кликните дважды по URL адресу в адресной строке браузера, возможно, вы неверно ввели адрес страницы. <li>
                            <li>Очистите кэш вашего браузера. Кэшированная версия страницы, на которую вы пытались зайти, может быть причиной возникновения ошибки. <li>
                            <li>Попробуйте залогиниться снова. <li>
                        </ol>
                    </div>
                </article>
            </div>
        </div>
    </div>
</section>