<?php
/**
 * Ошибка 404 (Not Found En_GB).
 * 
 * Шаблон страницы.
 * 
 * @author Anton Tivonenko <anton.tivonenko@gmail.com>
 * @copyright Copyright (c) 2015 GearMagic Web-студия
 * @package Theme
 * @subpackage Impact
 * @since 1.0
 */

$this->title('Error 404 (Not Found)');
?>
<section class="blog">
    <div class="container aos-init aos-animate" data-aos="fade-up">
        <div class="row g-5">
            <div class="col-lg-12">
                <article class="blog-details">
                    <h2 class="title">Error 404 (Not Found)</h2>
                    <div class="content">
                        <p>You are trying to access a page that may have been deleted.</p>
                        <ol>
                            <li>Please check that the address you are entering is correct and/or correct it..</li>
                            <li>Clear your browser's cache and try the page again.</li>
                            <li>Go to the main page of the site and try to find the information you need by clicking on the links.</li>
                            <li>Look for the page in search engines - the page may have been published at a new address.</li>
                        </ol>
                    </div>
                </article>
            </div>
        </div>
    </div>
</section>