<?php
/**
 * Ошибка 404 (Not Found).
 * 
 * Шаблон страницы.
 * 
 * @author Anton Tivonenko <anton.tivonenko@gmail.com>
 * @copyright Copyright (c) 2015 GearMagic Web-студия
 * @package Theme
 * @subpackage Impact
 * @since 1.0
 */

$this->title('Ошибка 404 (Не найдено)');
?>
<section class="blog">
    <div class="container aos-init aos-animate" data-aos="fade-up">
        <div class="row g-5">
            <div class="col-lg-12">
                <article class="blog-details">
                    <h2 class="title">Ошибка 404 (Не найдено)</h2>
                    <div class="content">
                        <p>Вы пытаетесь получить доступ к странице, которая возможно была удалена.</p>
                        <ol>
                            <li>Проверьте корректность вводимого вами адреса и/или скорректируйте его.</li>
                            <li>Очистите кэш вашего браузера и попробуйте обратиться к странице вновь.</li>
                            <li>Перейдите на главную страницу сайта и попробуйте найти нужную информацию, переходя по ссылкам.</li>
                            <li>Поищите страницу в поисковых системах — возможно страница была опубликована по новому адресу.</li>
                        </ol>
                    </div>
                </article>
            </div>
        </div>
    </div>
</section>