<?php
/**
 * Главная страница.
 * 
 * Шаблон страницы.
 * 
 * @author Anton Tivonenko <anton.tivonenko@gmail.com>
 * @copyright Copyright (c) 2015 GearMagic Web-студия
 * @package Theme
 * @subpackage Impact
 * @since 1.0
 * 
 * @var \Gm\View\View $this
 */

?>
<?= $this->renderFrom('../sections/about') ?>
<?= $this->renderFrom('../sections/clients') ?>
<?= $this->renderFrom('../sections/stats-counter') ?>
<?= $this->renderFrom('../sections/call-to-action') ?>
<?= $this->renderFrom('../sections/services') ?>
<?= $this->renderFrom('../sections/testimonials') ?>
<?= $this->renderFrom('../sections/portfolio') ?>
<?= $this->renderFrom('../sections/team') ?>
<?= $this->renderFrom('../sections/pricing') ?>
<?= $this->renderFrom('../sections/faq') ?>
<?= $this->renderFrom('../sections/recent-posts') ?>
<?= $this->renderFrom('../sections/contact') ?>
