<?php
/**
 * Главная страница (en_GB).
 * 
 * Шаблон страницы.
 * 
 * @author Anton Tivonenko <anton.tivonenko@gmail.com>
 * @copyright Copyright (c) 2015 GearMagic Web-студия
 * @package Theme
 * @subpackage Impact
 * @since 1.0
 * 
 * @var \Gm\View\View $this
 */

?>
<?= $this->renderFrom('../sections/about-en_GB') ?>
<?= $this->renderFrom('../sections/clients-en_GB') ?>
<?= $this->renderFrom('../sections/stats-counter-en_GB') ?>
<?= $this->renderFrom('../sections/call-to-action-en_GB') ?>
<?= $this->renderFrom('../sections/services-en_GB') ?>
<?= $this->renderFrom('../sections/testimonials-en_GB') ?>
<?= $this->renderFrom('../sections/portfolio-en_GB') ?>
<?= $this->renderFrom('../sections/team-en_GB') ?>
<?= $this->renderFrom('../sections/pricing-en_GB') ?>
<?= $this->renderFrom('../sections/faq-en_GB') ?>
<?= $this->renderFrom('../sections/recent-posts-en_GB') ?>
<?= $this->renderFrom('../sections/contact-en_GB') ?>
